### ISSUE TITLE
Access Denied on lanacion when url ends in ?outputType=amp/

### ISSUE THREAD

**Issue by yoasif** [da2x/amp2html#27] opened 2022-01-23 00:50 UTC
Testing in Firefox release on desktop.

1. Install Amp to html
2. navigate to https://www.google.com/amp/s/www.lanacion.com.ar/economia/dolar-reunion-ultima-hora-banco-central-analizar-nid2301134/%3foutputType=amp

What happens:

I end up on https://www.lanacion.com.ar/economia/dolar-reunion-ultima-hora-banco-central-analizar-nid2301134/?outputType=amp/ but the page says

```
Access Denied
You don't have permission to access "http://www.lanacion.com.ar/economia/dolar-reunion-ultima-hora-banco-central-analizar-nid2301134/?" on this server.
```

Expected result:

I end up on https://www.lanacion.com.ar/economia/dolar-reunion-ultima-hora-banco-central-analizar-nid2301134/

Oddly enough, on desktop, I end up on this page on Chromium and Firefox *anyway*.  

It looks like this is due to the extension not stripping the `?outputType=amp/` from the url. 

I found this link on https://www.reddit.com/r/argentina/comments/sa1trs/salario_m%C3%ADnimo_en_argentina/httbjpe/

**Comment by da2x** [comment] 2022-01-24 03:41
Please see issue #23. How did you get these URLs?

**Comment by da2x** [comment] 2022-01-24 04:30
Duplicate of #23. Thanks for the report! Made me have another look.

**Closed by da2x** 2022-01-24 04:30 UTC

**Comment by yoasif** [comment] 2022-01-24 04:33
I got the URLs by user shares from reddit. You can find them by navigating to https://www.reddit.com/user/AmputatorBot/comments/ and clicking omm "context" under the links and looking for the originally posted AMP links.
