### ISSUE TITLE
"Page not found" on Evening Standard when url ends in %3Famp

### ISSUE THREAD

**Issue by yoasif** [da2x/amp2html#26] opened 2022-01-23 00:28 UTC
Testing in Firefox release on desktop.

1. Install Amp to html
2. navigate to https://www.google.com/amp/s/www.standard.co.uk/news/uk/russian-royal-navy-english-channel-english-russian-federation-b930489.html%3Famp

What happens:

I end up on https://www.standard.co.uk/news/uk/russian-royal-navy-english-channel-english-russian-federation-b930489.html%3famp

Expected result:

I end up on https://www.standard.co.uk/news/uk/russian-royal-navy-english-channel-english-russian-federation-b930489.html

Oddly enough, on desktop, I end up on this page on Chromium and Firefox *anyway*.  

It looks like this is due to the extension not stripping the `%3Famp` from the url. 

I found this link on https://www.reddit.com/r/worldnews/comments/s9x737/germany_blocks_estonian_weapons_to_ukraine/htt016s/ (the word "ships" is linked).

**Comment by da2x** [comment] 2022-01-24 04:30
Duplicate of #23. Thanks for the report!

**Closed by da2x** 2022-01-24 04:30 UTC
