### ISSUE TITLE
Works poorly on Google News

### ISSUE THREAD

**Issue by interfect** [da2x/amp2html#6] opened 2018-02-22 23:17 UTC
When using Google News in Firefox for Android with this extension installed, clicking a link to an AMP story brings up the normal AMP page. Only if I refresh do I see the extension do anything.

When I do refresh, I get a "redirect notice" from Google, like `https://www.google.com/url?q=https://www.cnbc.com/2018/02/22/california-agriculture-sees-wave-of-immigration-audits.html#pt0-251767`, asking me to confirm that I really want to go to the URL of the original page. I think the page code is able to intercept the extension's redirect somehow.

The extension should work on AMP pages from Google News without having to refresh the page, and it should always redirect regardless of any page code that tries to catch redirects.

**Comment by da2x** [comment] 2018-02-25 16:40
This is a duplicate of issue #5. There will be another version upgrade in a day or two addressing this issue.

**Closed by da2x** 2018-02-25 16:40 UTC
Labels: duplicate
